### ISSUE TITLE
Java binary as input specified as dir, analysis runs to complete but errors

### ISSUE THREAD

**Issue by eemcmullan** [konveyor/kantra#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

latest

### Priority

Major

### Expected Behavior

Should find binary in dir and complete analysis successfully. 

### How Reproducible

Always (Default)

### Anything else?

Currently, rules error with
`'open /opt/input/source/pom.xml: no such file or directory'`

**Comment by pranavgaikwad** [comment]
@eemcmullan I dont understand "input specified as dir", if a binary is passed, how could it be a dir?

**Comment by eemcmullan** [comment]
@pranavgaikwad  Yes to the second part. Will close this issue then
