### ISSUE TITLE
Inconsistency between matched rules with Windup

### ISSUE THREAD

**Issue by eemcmullan** [konveyor/kantra#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

latest

### Priority

Critical

### Current Behavior

Running analysis on the same application with target and custom rule can match in windup, but not kantra, and vice versa.

### How Reproducible

Always (Default)

### Steps To Reproduce

Example 1:
`kantra  analyze --input /Users/emilymcmullan/java_bin_example/jee-example-app-1.0.0.ear --output ./output --target eap7 --rules /Users/emilymcmullan/custom-rules/javax-package-custom.windup.xml`

The custom rule is unmatched in analysis output:

```
unmatched:
  - javax-package-00001
```

With Windup:

`windup-cli --input /Users/emilymcmullan/java_bin_example/jee-example-app-1.0.0.ear --target eap7 --output /Users/emilymcmullan/output-windup --userRulesDirectory /Users/emilymcmullan/java_xml_rule`

In report as an issue:
`javax.* packages must be renamed to jakarta.* for Jakarta EE9 compatibility.`

Example 2:
`kantra analyze --input /Users/emilymcmullan/kantra-demo/example-applications/example-1 --output ./output2 --target cloud-readiness --rules /Users/emilymcmullan/java_xml_rule-jni`

The custom rule is matched in analysis output:
```
- description: This ruleset detects Java Native Interface (JNI) and Java Native Access (JNA) code, which may be problematic when migrating an application to a cloud environment.
  violations:
    jni-native-code-00000-test:
      description: |-
        Java native libraries (JNI, JNA)
```

In Windup:
`./windup-cli --input /Users/emilymcmullan/kantra-demo/example-applications/example-1 --target cloud-readiness --output /Users/emilymcmullan/output-windup2 --userRulesDirectory /Users/emilymcmullan/java_xml_rule-jni`

This custom rule is not found as an issue in report.

### Environment

```markdown
- OS: Mac
```

### Anything else?

```
<ruleset xmlns="http://windup.jboss.org/schema/jboss-ruleset" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="javax-package" xsi:schemaLocation="http://windup.jboss.org/schema/jboss-ruleset http://windup.jboss.org/schema/jboss-ruleset/windup-jboss-ruleset.xsd">
    <metadata>
        <description> This ruleset provides analysis of applications that use RESTEasy 3.0 and may require individual attention when migrating to RESTEasy 3.6. </description>
        <dependencies>
            <addon id="org.jboss.windup.rules,windup-rules-javaee,3.0.0.Final"/>
            <addon id="org.jboss.windup.rules,windup-rules-java,3.0.0.Final"/>
        </dependencies>
    </metadata>
    <rules>
        <rule id="javax-package-00001">
            <when>
                <javaclass references="javax.{*}">
                    <location>IMPORT</location>
                </javaclass>
            </when>
            <perform>
                <hint title="CUSTOM RULE for javax.* package import" effort="1" category-id="potential">
                    <message>`javax.*` packages must be renamed to `jakarta.*` for Jakarta EE9 compatibility.</message>
                    <link title="Renamed Packages" href="https://github.com/wildfly-extras/batavia/blob/master/impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/jakarta-renames.properties"/>
                    <tag>tag</tag>
                </hint>
            </perform>
        </rule>
    </rules>
</ruleset>
```

**Comment by pranavgaikwad** [comment]
@eemcmullan The second one (example-application app + custom rule) is a non-issue. It has to be a bug in Windup or some configuration thing not creating an issue. The first one, however, seems like an issue we need to solve in analyzer-lsp. I will investigate it and create an appropriate issue on analyzer.

**Comment by eemcmullan** [comment]
Related to #76
