### ISSUE TITLE
[BUG] Analysis failure on spring-music app, unknown error

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/kantra#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

Latest from 11/8, image id ce436ace613e

### Priority

Major

### Current Behavior

$ time ./analyze_spring_music.sh
INFO[0000] running source code analysis                  args="--provider-settings=/opt/input/config/settings.json --rules=/opt/rulesets/ --output-file=/opt/output/output.yaml --context-lines=100 --dep-label-selector=(!konveyor.io/dep-source=open-source) --verbose=4 --label-selector=((konveyor.io/target=quarkus || konveyor.io/target=jakarta-ee || konveyor.io/target=cloud-readiness) && konveyor.io/source) || (discovery)" input=/Users/jmatthews/git/jwmatthews/kyma_poc/data/spring-music-original log=/Users/jmatthews/git/jwmatthews/kyma_poc/data/example_reports/spring-music-original/analysis.log output=/Users/jmatthews/git/jwmatthews/kyma_poc/data/example_reports/spring-music-original volumes="{\"/Users/jmatthews/git/jwmatthews/kyma_poc/data/example_reports/spring-music-original\":\"/opt/output\",\"/Users/jmatthews/git/jwmatthews/kyma_poc/data/spring-music-original\":\"/opt/input/source\",\"/var/folders/l1/1b7gzz8n02b5nrtdq51bnj4r0000gn/T/analyze-config-19676531\":\"/opt/input/config\",\"/var/folders/l1/1b7gzz8n02b5nrtdq51bnj4r0000gn/T/m2-repo-627581428\":\"/root/.m2\"}"
INFO[0000] generating analysis log in file               file=/Users/jmatthews/git/jwmatthews/kyma_poc/data/example_reports/spring-music-original/analysis.log
INFO[0901] running dependency analysis                   args="--provider-settings=/opt/input/config/settings.json --rules=/opt/rulesets/ --output-file=/opt/output/output.yaml --context-lines=100 --dep-label-selector=(!konveyor.io/dep-source=open-source) --verbose=4 --label-selector=((konveyor.io/target=quarkus || konveyor.io/target=jakarta-ee || konveyor.io/target=cloud-readiness) && konveyor.io/source) || (discovery)" input=/Users/jmatthews/git/jwmatthews/kyma_poc/data/spring-music-original log=/Users/jmatthews/git/jwmatthews/kyma_poc/data/example_reports/spring-music-original/dependency.log output=/Users/jmatthews/git/jwmatthews/kyma_poc/data/example_reports/spring-music-original
INFO[0901] generating dependency log in file             file=/Users/jmatthews/git/jwmatthews/kyma_poc/data/example_reports/spring-music-original/dependency.log
ERRO[0915] container run error                           error="exit status 1"
ERRO[0915] failed to run analysis                        error=
Error: 

real	15m15.745s
user	0m0.165s
sys	0m0.186s
./analyze_spring_music.sh  0.17s user 0.19s system 0% cpu 15:15.76 total

$ cat /Users/jmatthews/git/jwmatthews/kyma_poc/data/example_reports/spring-music-original/dependency.log
time="2023-11-08T19:47:46Z" level=error msg="grpc unable to get info" error="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp [::1]:39119: connect: connection refused\"" logger=go provider=grpc
time="2023-11-08T19:47:49Z" level=error msg="failed to resolve sources jar for location" error="open /opt/input/source/pom.xml: no such file or directory" location=/opt/input/source provider=java
time="2023-11-08T19:47:52Z" level=error msg="failed to get list of dependencies for provider" error="exit status 1" provider=go
time="2023-11-08T19:47:59Z" level=info msg="unable to get dependencies, using fallback" error="{\"Stderr\":null}" provider=java
time="2023-11-08T19:47:59Z" level=error msg="failed to get list of dependencies for provider" error="open /opt/input/source/pom.xml: no such file or directory" provider=java
time="2023-11-08T19:47:59Z" level=info msg="provider does not have dependency capability" provider=builtin
time="2023-11-08T19:47:59Z" level=info msg="failed to get dependencies from all given providers"

$ tail /Users/jmatthews/git/jwmatthews/kyma_poc/data/example_reports/spring-music-original/analysis.log
time="2023-11-08T19:47:43Z" level=error msg="failed to evaluate rule" error="open /opt/input/source/pom.xml: no such file or directory" ruleID=quarkus-picocli-00000
time="2023-11-08T19:47:43Z" level=info msg="unable to get dependencies, using fallback" error="{\"Stderr\":null}" provider=java
time="2023-11-08T19:47:43Z" level=info msg="rule returned" rule=quarkus-picocli-00010
time="2023-11-08T19:47:43Z" level=error msg="failed to evaluate rule" error="open /opt/input/source/pom.xml: no such file or directory" ruleID=quarkus-picocli-00010
time="2023-11-08T19:47:45Z" level=info msg="unable to get dependencies, using fallback" error="{\"Stderr\":null}" provider=java
time="2023-11-08T19:47:45Z" level=info msg="rule returned" rule=quarkus-resteasy-multipart-00000
time="2023-11-08T19:47:45Z" level=error msg="failed to evaluate rule" error="open /opt/input/source/pom.xml: no such file or directory" ruleID=quarkus-resteasy-multipart-00000
time="2023-11-08T19:47:45Z" level=info msg="unable to get dependencies, using fallback" error="{\"Stderr\":null}" provider=java
time="2023-11-08T19:47:45Z" level=info msg="rule returned" rule=quarkus-resteasy-multipart-00010
time="2023-11-08T19:47:45Z" level=error msg="failed to evaluate rule" error="open /opt/input/source/pom.xml: no such file or directory" ruleID=quarkus-resteasy-multipart-00010

# Full analysis log is a gist below

$ gist /Users/jmatthews/git/jwmatthews/kyma_poc/data/example_reports/spring-music-original/analysis.log
https://gist.github.com/jwmatthews/2ca6ed240c7c910a4de1cd3c6d760240

### Expected Behavior

Success

### How Reproducible

Always (Default)

### Steps To Reproduce

Seems to be reproducible

I've bounced the podman VM as well and repeated failure.
I've seen failure at ~6 minutes in and at ~15 minutes in.

Running with podman started via: https://github.com/konveyor/kantra/blob/main/hack/darwin_restart_podman_machine.sh
(4 CPUs and 8GB RAM)

$ git clone https://github.com/cloudfoundry-samples/spring-music.git spring-music-original

$ cat analyze_spring_music.sh 
SOURCE_DIR=spring-music-original
OUTDIR=$PWD/example_reports/${SOURCE_DIR}
mkdir -p $OUTDIR
time ./kantra analyze -i $PWD/$SOURCE_DIR -t "quarkus" -t "jakarta-ee" -t "cloud-readiness" -o $OUTDIR --overwrite

### Environment

```markdown
- OS: MacOS M1Max
```

**Comment by jwmatthews** [comment]
We think this failure is due to the project using gradlew and lack of a pom.xml and analyzer-lsp not yet able to handle this scenario.

**Comment by eemcmullan** [comment]
Closing as we now have https://github.com/konveyor/kantra/issues/142 to track supporting this case
