### ISSUE TITLE
[RFE] Multi-language support

### ISSUE THREAD

**Issue by eemcmullan** [konveyor/kantra#142]
As of now, kantra assumes the analysis of Java applications. We need to add support for other language providers from https://github.com/konveyor/analyzer-lsp. 

See https://github.com/konveyor/enhancements/pull/165 for details.

**Comment by ascheman** [comment]
Even for Java you should distinguish between several build systems (Majors are Maven and Gradle, but there are several others around). Even if a pom.xml is around the project might use Gradle as primary build system.

**Comment by dymurray** [comment]
Related: https://github.com/konveyor/analyzer-lsp/issues/470

**Comment by mail2nadeem92** [comment]
Hello @eemcmullan,

Please add a size label (size/XS, size/S, size/M, size/L, size/XL) to assist in the Konveyor planning process.
