### ISSUE TITLE
[BUG] Analysis.log file does not contain the complete log

### ISSUE THREAD

**Issue by hhpatel14** [konveyor/kantra#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

NA

### Priority

Major

### Current Behavior

Analysis logs are missing details  [analysis.log](https://github.com/konveyor/kantra/files/13977462/analysis.log)

### Expected Behavior

 analysis.log file with complete log.  [analysis.log](https://github.com/konveyor/kantra/files/13977693/analysis.log)

### How Reproducible

Always (Default)

### Steps To Reproduce

- Get the example application to run analysis on
 git clone https://github.com/konveyor/example-applications

- List available target technologies
kantra analyze --list-targets

- Run analysis with a specified target technology
kantra analyze --input <path-to/example-applications/example-1>  --output /output-location --target cloud-readiness

### Environment

```markdown
- OS:
```

**Comment by eemcmullan** [comment]
@hhpatel14 is there anything in particular you're looking for in the current logs? It looks like we've cleaned up some of the info that is logged to make it more consumable to the user.

**Comment by eemcmullan** [comment]
Could not reproduce
