### ISSUE TITLE
[Feature] Support the ability to run kantra inside of a single container image

### ISSUE THREAD

**Issue by dymurray** [konveyor/kantra#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

0.3.0

### Priority

Major

### Current Behavior

Today kantra is expected to run on folks machines and spin up containers to run the analysis engine.

### Expected Behavior

It would be really nice if a user could do `docker run -v <output_dir>:/tmp/<output_dir> -v <input_dir>:/tmp/<input_dir> quay.io/konveyor/kantra -- analyze --input /tmp/<input_dir> --output /tmp/<output_dir>` and have the entire analysis run in a single image.

This would remove the burden on the user significantly.

**Comment by eemcmullan** [comment]
Closing as decided to not complete

**Comment by edeandrea** [comment]
Just so its clear - not implementing this requirement requires that a user run/install kantra directly on their machines. There is no option to offer kantra as a container image that someone could then run.

**Comment by eemcmullan** [comment]
Was discussing with @dymurray and @pranavgaikwad and we decided on a work-around using analyzer-lsp directly, as a huge percentage of kantra's code is to support how it currently runs (each command in a new container). This means integrating this issue would require a huge re-write. I think an issue or instructions were created for the alternative, but we possibly forgot to share. @dymurray I can't remember if this has been done. If not, I don't mind doing so.
