### ISSUE TITLE
[Feature] Make platform CLI binaries available with GitHub releases

### ISSUE THREAD

**Issue by edeandrea** [konveyor/kantra#159]
When doing a release, make the CLI binaries for the various platforms (linux, macos, windows) available as downloadable assets for the release.

**Comment by pranavgaikwad** [comment]
@edeandrea We have now added workflow to add binaries to the assets, we also fixed the existing 0.3.0 release. Please find the binaries  here https://github.com/konveyor/kantra/releases/tag/v0.3.0
