### ISSUE TITLE
Rename `PODMAN_BIN` to `CONTAINER_TOOL` with backward compatibility

### ISSUE THREAD

**Issue by dagood** [konveyor/kantra#168]
This came up in https://github.com/konveyor/kantra/pull/165: now that kantra will automatically fall back to `docker` if `podman` isn't present, `PODMAN_BIN` doesn't make quite as much sense. Renaming it to `CONTAINER_TOOL` would help clarify what the override is actually overriding.

Continuing to accept `PODMAN_BIN` and forwarding it to `CONTAINER_TOOL` means this doesn't need to be a breaking change. (I don't mind if this is a breaking change myself, though, just an idea.)

A name other than `CONTAINER_TOOL` is fine with me, it does seem like an easy pick though. I also took a look in k8s and see that name being used: https://github.com/search?q=org%3Akubernetes-sigs+CONTAINER_TOOL&type=code

**Comment by soham4abc** [comment]
Hey, I issued a PR that might close this issue!!
