### ISSUE TITLE
[BUG] Seeing a significant difference in the time taken to complete the analysis (Windup:3 min34 sec vs Kantra:211m14.944) with the airsonic.war sample

### ISSUE THREAD

**Issue by kthatipally** [konveyor/kantra#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

v0.3.0

### Priority

Undefined (Default)

### Issue: 
We've observed a substantial variance (**_~3 hrs difference_**) in the analysis duration between Windup and Kantra for airsonic.war file. 

More details about the sample run:

- **Sample:** [https://github.com/airsonic/airsonic/releases/tag/v10.6.2](https://github.com/airsonic/airsonic/releases/tag/v10.6.2) (airsonic.war)
-  **Windup version used:** 6.3.4.Final
- **Kantra version used:** v0.3.0
- **Time taken to complete the analysis and generate static report:** _3.4 minutes._
-  **Time taken to complete the analysis and generate static report:** _Using podman + kantra with v0.3.0, 211m14.944._
-  **Arguments:** --input, --output, --overwrite, --target (cloud-readiness)
- Kantra Command: `time ./kantra analyze --input airsonic.war --output report-kantra-v0.3.0 -target cloud-readiness --overwrite` 
-  windup command: `time ./windup-cli --input airsonic.war  --target cloud-readiness --output report-windup --batchMode   --overwrite`
- **Static report data after analysis:** 
          _Windup:_
              - Total Incidents: 1190 
              - Total Issues: 51
              - Total Tags: 45
              - Story Points 1145          
          _Kantra_:
              - Total Incidents: 6489 
              - Total Issues: 15
              - Total Tags: 12
              - Story Points: 24160

### Expected Behavior

Our expectation is for Kantra to complete the analysis in a timeframe comparable to Windup. Additionally, we are keen on understanding any design differences that might contribute to this discrepancy, considering both tools operate with different engines.

### How Reproducible

Always (Default)

### Steps To Reproduce

OS: Linux
- Kantra Command: 
`podman cp $(podman create --name kantra-download quay.io/konveyor/kantra:v0.3.0):/usr/local/bin/kantra . && podman rm kantra-download`
`export RUNNER_IMG=quay.io/konveyor/kantra:v0.3.0`
`time ./kantra analyze --input airsonic.war --output report-kantra-v0.3.0 -target cloud-readiness --overwrite`

- Windup command: 
Download and extract https://[windup.github.io/downloads/](https://windup.github.io/downloads/) zip: 
cd [WindupRootFolder]/bin
 `time ./windup-cli --input airsonic.war --target cloud-readiness --output report-windup --batchMode --overwrite`

### Environment

```markdown
- OS:
  -     Fedora Linux
  -     Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  -     32 GiB RAM
  -     Running on an SSD
```

### Anything else?

Attached the report zip: 
[kantra-report-2.zip](https://github.com/konveyor/kantra/files/14513674/kantra-report-2.zip)
[windup-report.zip](https://github.com/konveyor/kantra/files/14513762/windup-report.zip)

**Comment by pranavgaikwad** [comment]
@kthatipally Thank you for reporting the issue. I am able to reproduce this and my initial investigation suggests that we are decompiling more files than necessary that may be causing the slowdown. We are looking into a solution.

**Comment by pranavgaikwad** [comment]
We found the issue responsible for consuming a big chunk of time, fixed here https://github.com/konveyor/analyzer-lsp/pull/530. This should bring down the overall time down to 10m from over 200m total. There's still a follow up issue we would like to solve to even improve on performance captured here: https://github.com/konveyor/kantra/issues/172

**Comment by pranavgaikwad** [comment]
Hey folks, we have addressed all performance issues in binary mode. @shawn-hurley also merged the last piece we needed to address the issue around incidents from open source deps https://github.com/konveyor/analyzer-lsp/pull/556. I think this issue can  now be closed. Please feel free to re-open if needed.
