### ISSUE TITLE
Add support for running containers for each provider & the analyzer engine 

### ISSUE THREAD

**Issue by eemcmullan** [konveyor/kantra#190]
Once the discovery process is completed, a container will need to be started for the analyzer engine, as well as a container for each provider found during the discovery process. We will probably want to use a podman pod for this.

**Comment by mail2nadeem92** [comment]
Hello @eemcmullan,

Please add a size label (size/XS, size/S, size/M, size/L, size/XL) to assist in the Konveyor planning process.
