### ISSUE TITLE
Use providerSettings config to pass provider options

### ISSUE THREAD

**Issue by eemcmullan** [konveyor/kantra#199]
Because we will soon support multiple providers with kantra, we want to be able to pass individual provider options in a config file. Right now, we can pass a few Java-specific options via kantra cli. If we continue down this path with other providers, we will have an overwhelming number of flag options.

**Comment by mail2nadeem92** [comment]
Hello @eemcmullan,

Please add a size label (size/XS, size/S, size/M, size/L, size/XL) to assist in the Konveyor planning process.
