### ISSUE TITLE
[BUG] The provider container should be removed as it stop beforehand

### ISSUE THREAD

**Issue by kpunwatk** [konveyor/kantra#237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

latest

### Priority

Major

### Current Behavior

For successful run at the end we observe the error message, As it's not expected as the provider container stop it beforehand

`ERRO[0157] failed to remove container container=cYmqdvxrPywzgLTc error="exit status 1" `

Jira Issue link https://issues.redhat.com/browse/MTA-2820 

### How Reproducible

Always (Default)

### Environment

```markdown
- OS:
```

**Comment by eemcmullan** [comment]
Fixed in https://github.com/konveyor/kantra/pull/235
