### ISSUE TITLE
[BUG] websphere-catchall rule to be converted into Tags

### ISSUE THREAD

**Issue by kpunwatk** [konveyor/kantra#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

latest

### Priority

Minor

### Current Behavior

Ran an analysis on the Kantra CLI with the Daytrader app and noticed that one of the rules has an effort value of 0

websphere-catchall-00000 rule need to converted into Tags

Jira issue link https://issues.redhat.com/browse/MTA-2825

### How Reproducible

Always (Default)

### Environment

```markdown
- OS:
```

**Comment by shawn-hurley** [comment]
This is fixed with ruleset change https://github.com/konveyor/rulesets/pull/80
