### ISSUE TITLE
The issue files are empty for Go application

### ISSUE THREAD

**Issue by kpunwatk** [konveyor/kantra#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

latest

### Priority

Major

### Current Behavior

The issue files are empty running and analysis using goalng application from analyzer-lsp/examples/golang and rule file [golang-dep-rules.yaml](https://gist.github.com/eemcmullan/6cd3cc89b9f5b1d8aa757b2ed64677b4) and command run
$ ./kantra analyze --input=/home/path/analyzer-lsp/examples/golang --output=output_dir --rules /home/path/golang_rules/golang-dep-rules.yaml 
![Screenshot from 2024-05-21 08-32-58](https://github.com/konveyor/kantra/assets/87791967/7baac2eb-5853-4db2-989a-c6896bc8f764)

### Expected Behavior

Should display a message provide in rule

### How Reproducible

Always (Default)

### Environment

```markdown
- OS:
```

**Comment by eemcmullan** [comment]
Closing for https://github.com/konveyor/kantra/issues/285
