### ISSUE TITLE
[BUG] Some setting do not respect ENV variables

### ISSUE THREAD

**Issue by aufi** [konveyor/kantra#252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

main / latest

### Priority

Major

### Current Behavior

There is a mixture of Settings between ENV-based settings from https://github.com/konveyor/kantra/blob/main/cmd/settings.go (using github.com/codingconcepts/env lib) and package-level variables from version.go file https://github.com/konveyor/kantra/blob/main/cmd/version.go#L12-L16.

Current behaviour is that methods from https://github.com/konveyor/kantra/blob/main/cmd/settings.go#L55-L109 do not respect environment default from https://github.com/konveyor/kantra/blob/main/cmd/settings.go#L25-L33, but look to version.go https://github.com/konveyor/kantra/blob/main/cmd/version.go#L12-L16.

### Expected Behavior

Settings should use https://github.com/konveyor/kantra/blob/main/cmd/settings.go#L25-L33 as a primary source of truth without setting env variables on its own. So run `env.Set(c)` first and then modify its content in custom `load*` methods. This affect IMG_RUNNER, but also container engine and providers config.

### How Reproducible

Always (Default)

### Steps To Reproduce

```
cd cmd && go test .

package cmd

import (
	"os"
	"testing"
)

// Test RUNNER_IMG settings
func TestRunnerImgDefault(t *testing.T) {
	os.Unsetenv("RUNNER_IMG")	// Ensure empty variable
	s := &Config{}
	s.Load();
	if s.RunnerImage != "quay.io/konveyor/kantra:latest" {
		t.Errorf("Unexpected RUNNER_IMG default: %s", s.RunnerImage)
	}
}

func TestRunnerImgCustom(t *testing.T) {
	os.Setenv("RUNNER_IMG", "quay.io/some-contributor/my-kantra")
	s := &Config{}
	s.Load();
	if s.RunnerImage != "quay.io/some-contributor/my-kantra:latest" {
		t.Errorf("Unexpected RUNNER_IMG: %s", s.RunnerImage)
	}
}
```

### Environment

```markdown
- OS:
```

### Anything else?

Related PRs
- https://github.com/konveyor/kantra/pull/251
- https://github.com/konveyor/kantra/pull/222

**Comment by eemcmullan** [comment]
Fixed in https://github.com/konveyor/kantra/pull/253
