### ISSUE TITLE
[BUG] Report URL is not clickable

### ISSUE THREAD

**Issue by abrugaro** [konveyor/kantra#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

latest

### Priority

Undefined (Default)

### Current Behavior

When running an analysis, the URL of the static report is displayed at the end, however, the URL is formed as follows:

`file:/path/to/index.html`

This URL is not valid because it is missing two slashes after the colon, so it should be:

`file:///path/to/index.html`

Due to this difference, terminal clients do not recognize it as a URL and do not allow clicking on it.

### Expected Behavior

The URL displayed should be formed as follows:

`file:///path/to/index.html`

### How Reproducible

Always (Default)

### Steps To Reproduce

1. Execute an analysis on any app

### Environment

```markdown
- OS: Fedora 40
```

**Comment by eemcmullan** [comment]
Closed in https://github.com/konveyor/kantra/pull/269
