### ISSUE TITLE
[BUG] Network and volume cleaup doesn't complete correctly aafter run

### ISSUE THREAD

**Issue by jmontleon** [konveyor/kantra#282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

0.5.0 Beta 1

### Priority

Undefined (Default)

### Current Behavior

ERRO[5882] failed to remove network                      error="exit status 2" network=ndagNoZmusYllEBy
ERRO[5882] failed to remove volume                       error="exit status 2" volume=NhsLFdLqFpQYybfW

When i try to delete the volume I see it complains the pod is still running:
```
$ podman volume rm NhsLFdLqFpQYybfW
Error: volume NhsLFdLqFpQYybfW is being used by the following container(s): 48a700d344885ed167d3d0fbcb48c3caf0c907ced901c08a59d21a8ce769a420: volume is being used
```

```
$ podman ps
CONTAINER ID  IMAGE                                                     COMMAND       CREATED      STATUS      PORTS       NAMES
d7b8cd1764c5  quay.io/konveyor/java-external-provider:v0.5.0-beta.1     --port=44341  3 hours ago  Up 3 hours  14651/tcp   WzzDnBZOEshdCuYN
bebf9b839839  quay.io/konveyor/generic-external-provider:v0.5.0-beta.1  --port=34189  3 hours ago  Up 3 hours              xTMyinpQRrzFRmOT
```

### Expected Behavior

No errors.

### How Reproducible

Always (Default)

### Steps To Reproduce

1. `kantra analyze --input ./nexus-public/ --output ./nexus-public-cli`

### Environment

```markdown
- OS: Fedora 40
```

### Anything else?

I did inadvertently ctrl-c the prior run and restarted it after cleaning up the `nexus-public-cli`. It's possible this caused  the error later.

**Comment by eemcmullan** [comment]
Fixed in https://github.com/konveyor/kantra/pull/317
