### ISSUE TITLE
[BUG] running analysis fails unexpectedly 

### ISSUE THREAD

**Issue by Neilhamza** [konveyor/kantra#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

v0.5.0

### Priority

Blocker

### Current Behavior

tested configurations:
kantra latest
input app tackle-testapp-public
tager eap8

logs:
/usr/local/bin/kantra analyze --input /[REDACTED_PATH]/tackle-testapp-public --output /[REDACTED_PATH]/ --overwrite --target eap8

/usr/bin/podman run --rm --name [REDACTED_CONTAINER_NAME] --entrypoint /usr/local/bin/kantra --env RUN_MODE=container quay.io/konveyor/kantra:latest analyze --list-targets
Trying to pull quay.io/konveyor/kantra:latest...
Getting image source signatures

Copying blob sha256:[REDACTED]
Copying blob sha256:[REDACTED]
Copying blob sha256:[REDACTED]
Copying blob sha256:[REDACTED]
Copying config sha256:[REDACTED]
Writing manifest to image destination

time="2024-08-01T10:06:35+03:00" level=info msg="running source code analysis" args="[REDACTED_ARGS]" input=[REDACTED_INPUT] log=[REDACTED_LOG] output=[REDACTED_OUTPUT] volumes="[REDACTED_VOLUMES]"

time="2024-08-01T10:06:35+03:00" level=info msg="generating analysis log in file" file=[REDACTED_LOG_FILE]

/usr/bin/podman run --rm --name [REDACTED_CONTAINER_NAME] --network none --entrypoint /usr/local/bin/konveyor-analyzer -v [REDACTED_PATH]:/opt/input/source:z -v [REDACTED_PATH]:/opt/output:z -v /[REDACTED_PATH]:/opt/input/config:z -v /[REDACTED_PATH]:/root/.m2:z quay.io/konveyor/kantra:latest [REDACTED_SETTINGS]
Analysis failed
`

### How Reproducible

Always (Default)

### Environment

```markdown
TESTED ON IDEs
eclipse, vscode and IntelliJ
```

**Comment by eemcmullan** [comment]
@Neilhamza what error(s) occur? There should be an error in the output from kantra, or in your output dir in `analysis.log`. You can specify `--log-level 10` if needed.
