### ISSUE TITLE
[RFE] Add a `version` subcommand

### ISSUE THREAD

**Issue by jmle** [konveyor/kantra#328]
It would be useful to have the version hardcoded in the binary and be able to access it through a command or subcommand (either `kantra version` or `kantra --version`). Having multiple versions of kantra downloaded over time can make it confusing.

**Comment by aufi** [comment]
Could be related to https://github.com/konveyor/kantra/pull/154

**Comment by eemcmullan** [comment]
Resolved in https://github.com/konveyor/kantra/pull/154
