### ISSUE TITLE
[BUG] Containerless-Kantra : [Windows-Only - Java Project analysis] Fails to create static-report

### ISSUE THREAD

**Issue by kthatipally** [konveyor/kantra#362]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Konveyor version

https://github.com/konveyor/kantra/releases/tag/v0.6.0-alpha.2

### Priority

Undefined (Default)

### Current Behavior

I have run the analysis using the command: 

`.\windows-kantra.exe analyze-bin --input C:\testing\spring-petclinic\ --output .\output-spc --target cloud-readiness --overwrite`

The files Dependencies.yaml and output.yaml have been successfully created. However, there's a problem with generating the static-report due to an issue with the cp command for the static-report. Let me know if you need any more info. 

See the error below:

![Image](https://github.com/user-attachments/assets/7ec5be87-22df-4e56-9098-5d14d370784a)

### Expected Behavior

Analysis is run successfully, and the static-report is generated. 

### How Reproducible

Always (Default)

### Steps To Reproduce

1. OS: Windows
2. Run Command: `.\windows-kantra.exe analyze-bin --input C:\testing\spring-petclinic\ --output .\output-spc --target cloud-readiness --overwrite`
3. Run via windows-powershell

### Environment

- OS:  Windows

**Comment by kthatipally** [comment]
Hi @eemcmullan , 
Please find the attached analysis.log. 
static-report.log is empty. Let me know if you need more logs. [analysis.log](https://github.com/user-attachments/files/17561206/analysis.log)

**Comment by eemcmullan** [comment]
@kthatipally Sorry, forgot we did that there. Is it fair to say `xcopy` would be the equivalent command?

**Comment by kthatipally** [comment]
@eemcmullan , Yes, the xcopy command works on Windows. Would it be worth considering a platform-agnostic approach? We might be able to use or adapt a function like (https://github.com/konveyor/kantra/blob/d91946dc73f973cec1baaa213da223ce1d723165/cmd/analyze.go#L1077) to ensure cross-platform compatibility.

**Comment by eemcmullan** [comment]
Fixed in https://github.com/konveyor/kantra/pull/366
