### ISSUE TITLE
Analysis provides false positives on multiple rules

### ISSUE THREAD

**Issue by rromannissen** [konveyor/kantra#48]
### Environment

Kantra version: Latest (Retrieved on September 4th through the [documented command for Linux installs](https://github.com/konveyor-ecosystem/kantra#linux))
OS Fedora 36
podman version 4.3.1
[tackle-testapp](https://github.com/konveyor/tackle-testapp) application

### Description

Running analysis of both source code and binaries is triggering rules and generating issues that don't belong to the application that is being analyzed. In both cases, the target application is [tackle-testapp](https://github.com/konveyor/tackle-testapp). Please bear in mind that the application has a dependency with the config-utils library, which can only be retrieved from the Maven repository associated to that source code repository following [these instructions](https://github.com/konveyor/tackle-testapp/tree/main#testing-maven-integration). After the settings file is correctly configured, the binary can be generated with the `mvn package` command.

For binary, the following command was executed:

`kantra analyze --input=./customers-tomcat-0.0.1-SNAPSHOT.war --output=/home/rroman/kantraresults-binary --target=cloud-readiness --target=linux --log-level=7 | tee logbinary.log`

The log file produced by that execution is the following: [logbinary.log](https://github.com/konveyor-ecosystem/kantra/files/12526719/logbinary.log)

The report available in the _kantraresults-binary_ directory contains the following issues:

![Screenshot from 2023-09-05 19-32-34](https://github.com/konveyor-ecosystem/kantra/assets/15966456/0410027e-f50d-481d-9560-b672d3f5bbee)

The _Hardcoded IP Address_ issue seems to be right and points to the right file and the right location inside that file. The problem is the _File system - Java IO_ issue, which shouldn't have been triggered for all of the available occurrences. Checking the list of affected files, we can see that the file `PersistenceConfig.java` appears several times with a single incident, instead of appearing once with multiple incidents. Clicking on any of the file instances displays the right code snippet with what seems to be a random line highlighted:

![Screenshot from 2023-09-05 19-36-17](https://github.com/konveyor-ecosystem/kantra/assets/15966456/5593b30d-2f21-4aa8-9d7a-92d64fcaed72)

![Screenshot from 2023-09-05 19-36-32](https://github.com/konveyor-ecosystem/kantra/assets/15966456/ee63ad7e-51f6-44f5-8198-23cb471e7ab9)

Please note that no Java IO classes are imported nor instantiated in this class. It should also be noted that the _File system - Java IO_ issue  should have been triggered for one of the files available in the embedded config-utils library, but it is missing in the report. 

The source code was analyzed with the following command, passing exactly the same targets:

`kantra analyze --input=./tackle-testapp --output=/home/rroman/kantraresults-source --target=cloud-readiness --target=linux --log-level=6 | tee output.log`

The log file produced by that execution is the following: [output.log](https://github.com/konveyor-ecosystem/kantra/files/12526949/output.log)

In this case, the list of detected issues seems to be way bigger, as it seems that the analyzer is adding dependencies to the analysis scope, even though the `--analyzeKnownLibraries` flag hasn't been passed as a parameter:

![Screenshot from 2023-09-05 19-32-26](https://github.com/konveyor-ecosystem/kantra/assets/15966456/972129b8-3017-432f-a420-a7dda27e8a26)

It's hard to determine which of the rules are right, although there are some examples of the previously described random behavior. For example, for the _Java native libraries (JNI, JNA)_ rule, we can see that one of the occurrences in the GenericGroovyApplicationContext.class file highlights a comment as the incident:

![Screenshot from 2023-09-05 19-24-40](https://github.com/konveyor-ecosystem/kantra/assets/15966456/5f988da1-3faf-41db-a2f4-4e8e5b821a23)

![Screenshot from 2023-09-05 19-24-32](https://github.com/konveyor-ecosystem/kantra/assets/15966456/13b724bd-1af3-4ac0-81fa-3c9536bcdac7)

The snippet for the GenericGroovyApplicationContext.class file seems to be cropped, so it's hard to determine if there are imports in the file that could match any of the patterns for the rule that got triggered.

For example, for the _Java Mail API_ rule, there seems to be a correct match with the `MailSenderAutoConfiguration.class` file, but the line that got highlighted doesn't make any sense:

![Screenshot from 2023-09-05 19-37-43](https://github.com/konveyor-ecosystem/kantra/assets/15966456/962d7317-05d3-4aac-8e12-f7b60594f88e)

**Comment by eemcmullan** [comment]
Fixed in 0.5
