### ISSUE TITLE
OpenJDK target is missing

### ISSUE THREAD

**Issue by rromannissen** [konveyor/kantra#49]
### Environment

Kantra version: Latest (Retrieved on September 4th through the [documented command for Linux installs](https://github.com/konveyor-ecosystem/kantra#linux))
OS Fedora 36
podman version 4.3.1

### Description

The OpenJDK target is not included in the available target. That target is essential, as it included rules to migrate from Oracle JDK to OpenJDK. 

`$ kantra analyze --list-targets`
`available target technologies:
azure-aks
azure-appservice
azure-container-apps
azure-spring-apps
camel2
camel3
cloud-readiness
drools6
eap
eap6
eap7
eap8
eapxp2
eapxp3
fsw6
fuse6
hibernate-search5
hibernate4
hibernate5
hibernate5.1
hibernate5.3
hibernate6
hibernate6.1
hibernate6.2
jakarta-ee8
jakarta-ee9
java-ee6
java-ee7
jbpm6
linux
openjdk11
openjdk17
openjdk7
openliberty
quarkus
resteasy3
rhr
`

**Comment by sshveta** [comment]
![Screenshot from 2023-09-06 12-17-32](https://github.com/konveyor-ecosystem/kantra/assets/3866976/6f54facd-80a5-4c99-8d33-1bb2c3da53f2)

**Comment by sshveta** [comment]
The upstream UI shows openjdk as target . Does that mean it is not using the latest kantra CLI ? @pranavgaikwad

**Comment by pranavgaikwad** [comment]
@sshveta Kantra is a separate project. None of the Konveyor components use Kantra as of today.

**Comment by dymurray** [comment]
To clarify further @sshveta, Kantra uses the same underlying analyzer but the UX around specifying sources/targets and rulesets is fundamentally a different codebase.

So you properly identified that this is working and supported in the UI/Hub model, we want to ensure it's working from the CLI as well.

**Comment by sshveta** [comment]
Got it .Thanks @pranavgaikwad @dymurray

**Comment by pranavgaikwad** [comment]
Fixed now.
