### ISSUE TITLE
[BUG] Report crashes when navigating to Issues

### ISSUE THREAD

**Issue by jmle** [konveyor/kantra#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

N/A

### Priority

Critical

### Current Behavior

After analyzing an application, when I go to any of the Issues views, the application crashes and the view goes blank.

Getting the following on the browser console:
![image](https://github.com/konveyor/kantra/assets/4527008/3af71703-9c1e-41c1-b520-a6a737795ca3)

### Expected Behavior

The report issues should be viewable.

### How Reproducible

Always (Default)

### Steps To Reproduce

1. With the given environment, install kantra following [the instructions from the README](https://github.com/konveyor/kantra#linux).
2. Get the latest rules [from the rulesets repo](https://github.com/konveyor/rulesets).
3. Clone the [daytrader app](https://github.com/WASdev/sample.daytrader7).
4. Run kantra with the following options: `PODMAN_BIN=/usr/local/bin/docker ./kantra analyze --target cloud-readiness --input <daytrader-app dir> --output <output-dir> --rules <rulesets-repo-dir/default/generated>
5. Check the report and go to any of the "Issues" views.

### Environment

```markdown
- OS: Fedora 38
- Browser: Chrome (Version 117.0.5938.132)
- Containers: Docker version 24.0.6, build ed223bc
```

**Comment by jmle** [comment]
@pranavgaikwad this was about to be fixed, right?

**Comment by pranavgaikwad** [comment]
@jmle yeah, this should be already fixed in the new latest image
