### ISSUE TITLE
Kantra being stuck on mac x86

### ISSUE THREAD

**Issue by hhpatel14** [konveyor/kantra#91]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Konveyor version

N/A

### Priority

Major

### Current Behavior

When running `kantra analyze`, the analysis stops generating logs after a few minutes. The end of the log file does not show any failed steps or errors. Only two files are generated: `analysis.log` and `dependency.log` as output.

Potential solutions/reasons: 
1) The limit of open files in mounted volumes is 64, which is incredibly low (https://github.com/containers/podman/issues/16106#issuecomment-1317188581) Suggested by David 
2) Increase resources by changing podman machine settings. 

### Expected Behavior
```shell
$ ls ./output/ -1
analysis.log
dependencies.yaml
dependency.log
output.yaml
static-report
``` 
However, only two files are generated: `analysis.log` and `dependency.log` as output.

### How Reproducible

[Sometimes]

### Steps To Reproduce

Use this demo link to reproduce (https://github.com/konveyor/kantra#analyze-1)

### Environment

```markdown
- OS:
```

### Anything else?

Podman is running on macOS (Mac x86)

**Comment by jwmatthews** [comment]
On Mac M1

Setup Podman via:

```
podman machine init konveyor -v $HOME:$HOME -v /private/tmp:/private/tmp -v /var/folders/:/var/folders/
podman machine set konveyor --cpus 4 --memory 8192 --disk-size 100
podman machine set konveyor --rootful
podman system connection default konveyor
podman machine start konveyor
```


I hit this as well:
`time="2023-10-19T19:18:52Z" level=error msg="error writing output file" error="open /opt/output/output.yaml: too many open files" file=/opt/output/output.yaml`


Running against https://github.com/ivargrimstad/jakartaee-duke
this branch: https://github.com/ivargrimstad/jakartaee-duke/tree/start-tutorial
`
./kantra analyze -i /Users/jmatthews/git/SAMPLES/jakartaee-duke -t “jakarta-ee9+” -o /Users/jmatthews/RedHat/MTA/out`

Full output here:  https://gist.github.com/jwmatthews/5ef3fec3e3d5574921bb0256f106c8b4

**Comment by jwmatthews** [comment]
Resolved issue on Mac M1 with workaround here:  https://github.com/containers/podman/issues/16106#issuecomment-1317188581

```
podman machine stop <vmname>
ulimit -n unlimited
podman machine start <vmname>
```

Below is an example of a script I am using now on Mac M1 to create the podman machine

```
ulimit -n unlimited
podman machine init konveyor -v $HOME:$HOME -v /private/tmp:/private/tmp -v /var/folders/:/var/folders/
podman machine set konveyor --cpus 4 --memory 8192 --disk-size 100
podman machine set konveyor --rootful
podman system connection default konveyor
podman machine start konveyor
```

Example of a successful run
```

time ./kantra analyze -i /Users/jmatthews/git/SAMPLES/jakartaee-duke -t "jakarta-ee9+" -o /Users/jmatthews/RedHat/MTA/out | gist
https://gist.github.com/jwmatthews/814e619e2a8e81bece87a8ec4e2d32e6
./kantra analyze -i /Users/jmatthews/git/SAMPLES/jakartaee-duke -t  -o   0.25s user 0.39s system 0% cpu 3:32.72 total
gist  0.38s user 0.09s system 0% cpu 3:35.01 total
```

full output here if interested: https://gist.github.com/jwmatthews/814e619e2a8e81bece87a8ec4e2d32e6

**Comment by jwmatthews** [comment]
Summary of what we know:
Looks like 2 issues we need to handle in README for Mac:

1. Bump resource limits 'memory':  `podman machine set konveyor --cpus 4 --memory 8192`
2. Add an explicit `ulimit -n unlimited` on the Mac host, prior to starting podman machine

The issue we are seeing with file limits seems to be from the Mac side limiting the number of files allowed in a mounted volume
