### ISSUE TITLE
[MacOS]: Performance WindUp (~28 seconds) vs Kantra (~237 seconds) on sample app jakartaee-duke with target jakarta-ee

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/kantra#96]
I am seeing a noticeable performance difference between running Kantra and [WindUp](https://github.com/windup/windup) on the same source application and target on my Mac M1 Max (64GB)

Sample app:  https://github.com/ivargrimstad/jakartaee-duke/tree/start-tutorial
* Using the 'start-tutorial' branch

Environment: Mac M1 Max 64GB

### Run #1
```
time ./windup-cli --input /Users/jmatthews/git/jwmatthews/kantra/hack/tmp/jakartaee-duke --target jakarta-ee --output ./out --
52.59s user 2.58s system 206% CPU 
26.769 total
```
### Run #2 
```
time ./windup-cli --input /Users/jmatthews/git/jwmatthews/kantra/hack/tmp/jakartaee-duke --target jakarta-ee --output ./out --overwrite
61.67s user 3.10s system 232% CPU 
27.884 total
```

### Run #1 
```
time kantra analyze -i $PWD/tmp/jakartaee-duke -t "jakarta-ee9+" -o $PWD/tmp/out

real	3m50.204s
user	0m0.257s
sys	0m0.387s
./sample_run.sh  
0.30s user 0.46s system 0% CPU 
3:50.65 total
```
### Run #2

```
time kantra analyze -i $PWD/tmp/jakartaee-duke -t "jakarta-ee9+" -o $PWD/tmp/out

real	3m57.866s
user	0m0.252s
sys	0m0.366s
```

## Notes
I ran Kantra twice, thinking perhaps the first run had some delays pulling images, so second run was invoked soon after with the assumption images have been pulled (running on same podman machine VM)

```
$ podman machine info
Host:
  Arch: arm64
  CurrentMachine: kantra
  DefaultMachine: kantra
  EventsDir: /var/folders/l1/1b7gzz8n02b5nrtdq51bnj4r0000gn/T/podman-run--1/podman
  MachineConfigDir: /Users/jmatthews/.config/containers/podman/machine/qemu
  MachineImageDir: /Users/jmatthews/.local/share/containers/podman/machine/qemu
  MachineState: Running
  NumberOfMachines: 1
  OS: darwin
  VMType: qemu
Version:
  APIVersion: 4.7.1
  Built: 1696512066
  BuiltTime: Thu Oct  5 09:21:06 2023
  GitCommit: ef83eeb9c7482826672f3efa12db3d61c88df6c4
  GoVersion: go1.21.3
  Os: darwin
  OsArch: darwin/arm64
  Version: 4.7.1

```

```
$ podman machine inspect kantra
[
     {
          "ConfigPath": {
               "Path": "/Users/jmatthews/.config/containers/podman/machine/qemu/kantra.json"
          },
          "ConnectionInfo": {
               "PodmanSocket": {
                    "Path": "/Users/jmatthews/.local/share/containers/podman/machine/qemu/podman.sock"
               },
               "PodmanPipe": null
          },
          "Created": "2023-10-21T07:26:57.879808-04:00",
          "Image": {
               "IgnitionFilePath": {
                    "Path": "/Users/jmatthews/.config/containers/podman/machine/qemu/kantra.ign"
               },
               "ImageStream": "testing",
               "ImagePath": {
                    "Path": "/Users/jmatthews/.local/share/containers/podman/machine/qemu/kantra_fedora-coreos-38.20231014.2.0-qemu.aarch64.qcow2"
               }
          },
          "LastUp": "2023-10-21T07:26:57.879808-04:00",
          "Name": "kantra",
          "Resources": {
               "CPUs": 4,
               "DiskSize": 100,
               "Memory": 4096
          },
          "SSHConfig": {
               "IdentityPath": "/Users/jmatthews/.ssh/kantra",
               "Port": 55239,
               "RemoteUsername": "core"
          },
          "State": "running",
          "UserModeNetworking": true,
          "Rootful": false
     }
]

```

**Comment by jwmatthews** [comment]
Another run with Kantra on Mac M1 Max after bumping podman machine to have more resources
```
"Resources": {
               "CPUs": 8,
               "DiskSize": 100,
               "Memory": 16384
          },

```

## Run #1 (assume some time for fetching images as the VM was destroyed and recreated)

```
./kantra analyze -i $PWD/tmp/jakartaee-duke -t "jakarta-ee9+" -o $PWD/tmp/out  
0.24s user 0.30s system 0% CPU 
4:21.06 total
```

## Run #2 (in theory images have been pulled this should be a quicker run)
`
./kantra analyze -i $PWD/tmp/jakartaee-duke -t "jakarta-ee9+" -o $PWD/tmp/out  
 0.23s user 0.31s system 0% CPU 
4:07.99 total
`

**Comment by shawn-hurley** [comment]
Hey,

I notice the postman machine only has 4gb of memory, can we run with that a little higher?

I also notice the CPUs is 4 is that the max that windup was running as?

**Comment by jwmatthews** [comment]
Yeah, I posted another run with higher CPU's and memory after I did the initial, thinking maybe it was due to lower resources but I didn't see an improvement.   See the prior comment and I shared the specs and output

**Comment by shawn-hurley** [comment]
Yeah, I saw that after read the first email 😭 

I wonder if we are having an issue with volume mounts file I/o getting code snips. I have a sneaky suspicion that this could be pretty bad performance-wise, I don't think we are trying to do anything smart, batching up file reads, etc.

@pranavgaikwad @eemcmullan let me know what y'all think?

**Comment by shawn-hurley** [comment]
That is good to know; where is the bulk of the time spent in the conditions?

**Comment by pranavgaikwad** [comment]
@shawn-hurley See two traces - one on Linux, the other on Mac: 

On linux: 
![Screenshot from 2023-10-24 12-31-29](https://github.com/konveyor/kantra/assets/9839757/c0de9955-340a-4346-9606-bdcf46039712)

On Mac:

![Screenshot from 2023-10-24 12-31-34](https://github.com/konveyor/kantra/assets/9839757/b4d5b57a-fc19-47de-919b-f94b40c89cbc)

Notice that on average, the `file` and `filecontent` conditions are 100 times slower on Mac. I do think that analyzer itself isn't causing these issues, and there's very little we could do to solve this specific problem of `grep` or `find` running slower.  

The main reason seems to be the overhead in mounting the volumes via podman machine.

**Comment by shawn-hurley** [comment]
A quick test to be sure would be to build an image so that you don't have to mount things and run the analysis.

**Comment by jwmatthews** [comment]
Below was run on MacOS using Kantra (Macbook Pro M1Max)
CPU=4, MEM=8192

```
git clone https://github.com/deewhyweb/eap-coolstore-monolith.git coolstuff-javaee
time ./kantra analyze -i coolstuff-javaee -t "quarkus" -t "jakarta-ee" -t "cloud-readiness" -o ./out
real	33m41.188s
```

**Comment by shawn-hurley** [comment]
https://github.com/containers/podman/issues/16994#issuecomment-1805665534


just to note, it looks like Podman machine on Mac is a problem w/ mounting and file I/o. 

Do we think we can wait for this to be fixed in the underlying thing or not?

**Comment by ascheman** [comment]
FYI: I have similar (performance) problems with Docker (on Apple Silicon).

**Comment by shawn-hurley** [comment]
Tracking issue: https://github.com/coreos/fedora-coreos-tracker/issues/1548

I feel that we should wait until the above is done to further research

**Comment by shawn-hurley** [comment]
Closing this issues by #127

While the performance may not be one-to-one, this drastically reduces the time we take in file I/o. 

If we are still seeing drastic issues, can we add to #121 as I have a feeling we are going to see a difference in the network load on subsquent load because we don't have a shared .m2 while wind up will. 

Let me know if we feel this should be re-opened if the explanation is not sufficient

**Comment by jwmatthews** [comment]
> Below was run on MacOS using Kantra (Macbook Pro M1Max) CPU=4, MEM=8192
> 
> ```
> git clone https://github.com/deewhyweb/eap-coolstore-monolith.git coolstuff-javaee
> time ./kantra analyze -i coolstuff-javaee -t "quarkus" -t "jakarta-ee" -t "cloud-readiness" -o ./out
> real	33m41.188s
> ```

I re-ran today using :latest with https://github.com/konveyor/kantra/pull/127.
Huge improvement:  went from ~33mins to ~3.5 mins


$ time ./kantra analyze -i coolstuff-javaee -t "quarkus" -t "jakarta-ee" -t "cloud-readiness" -o ./out2     
INFO[0000] running source code analysis                  args="--provider-settings=/opt/input/config/settings.json --rules=/opt/rulesets/ --output-file=/opt/output/output.yaml --context-lines=100 --dep-label-selector=(!konveyor.io/dep-source=open-source) --verbose=4 --label-selector=((konveyor.io/target=quarkus || konveyor.io/target=jakarta-ee || konveyor.io/target=cloud-readiness) && konveyor.io/source) || (discovery)" input=/Users/jmatthews/git/jwmatthews/kyma_poc/data/coolstuff-javaee log=/Users/jmatthews/git/jwmatthews/kyma_poc/data/out2/analysis.log output=/Users/jmatthews/git/jwmatthews/kyma_poc/data/out2 volumes="{\"/Users/jmatthews/git/jwmatthews/kyma_poc/data/coolstuff-javaee\":\"/opt/input/source\",\"/Users/jmatthews/git/jwmatthews/kyma_poc/data/out2\":\"/opt/output\",\"/var/folders/l1/1b7gzz8n02b5nrtdq51bnj4r0000gn/T/analyze-config-4113444191\":\"/opt/input/config\"}"
INFO[0000] generating analysis log in file               file=/Users/jmatthews/git/jwmatthews/kyma_poc/data/out2/analysis.log
INFO[0126] running dependency analysis                   args="--provider-settings=/opt/input/config/settings.json --rules=/opt/rulesets/ --output-file=/opt/output/output.yaml --context-lines=100 --dep-label-selector=(!konveyor.io/dep-source=open-source) --verbose=4 --label-selector=((konveyor.io/target=quarkus || konveyor.io/target=jakarta-ee || konveyor.io/target=cloud-readiness) && konveyor.io/source) || (discovery)" input=/Users/jmatthews/git/jwmatthews/kyma_poc/data/coolstuff-javaee log=/Users/jmatthews/git/jwmatthews/kyma_poc/data/out2/dependency.log output=/Users/jmatthews/git/jwmatthews/kyma_poc/data/out2
INFO[0126] generating dependency log in file             file=/Users/jmatthews/git/jwmatthews/kyma_poc/data/out2/dependency.log
INFO[0197] generating static report                      args="/usr/local/bin/js-bundle-generator --analysis-output-list=/opt/output/output.yaml --deps-output-list=/opt/output/dependencies.yaml --output-path=/usr/local/static-report/output.js --application-name-list=coolstuff-javaee && cp -r /usr/local/static-report /opt/output" output=/Users/jmatthews/git/jwmatthews/kyma_poc/data/out2
INFO[0198] Static report created. Access it at this URL:  URL="file:/Users/jmatthews/git/jwmatthews/kyma_poc/data/out2/static-report/index.html"
./kantra analyze -i coolstuff-javaee -t "quarkus" -t "jakarta-ee" -t  -o   

0.13s user 0.18s system 0% cpu 3:19.08 total
